-- Sales Dashboard install script — runs when the app installs its supporting objects.
-- Idempotent: drops SALES if it exists before recreating.

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE sales PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE sales (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region     VARCHAR2(40) NOT NULL,
  amount     NUMBER(10, 2) NOT NULL,
  sale_date  DATE NOT NULL
);

INSERT INTO sales (region, amount, sale_date) VALUES ('North', 1250.00, DATE '2026-01-14');
INSERT INTO sales (region, amount, sale_date) VALUES ('South',  830.50, DATE '2026-01-22');
INSERT INTO sales (region, amount, sale_date) VALUES ('East',  2100.75, DATE '2026-02-03');
INSERT INTO sales (region, amount, sale_date) VALUES ('West',   615.00, DATE '2026-02-11');
INSERT INTO sales (region, amount, sale_date) VALUES ('North',  945.20, DATE '2026-02-19');
INSERT INTO sales (region, amount, sale_date) VALUES ('South', 1780.00, DATE '2026-03-05');
INSERT INTO sales (region, amount, sale_date) VALUES ('East',  1330.40, DATE '2026-03-14');
INSERT INTO sales (region, amount, sale_date) VALUES ('West',  2465.00, DATE '2026-03-21');
INSERT INTO sales (region, amount, sale_date) VALUES ('North',  520.75, DATE '2026-04-02');
INSERT INTO sales (region, amount, sale_date) VALUES ('South',  990.00, DATE '2026-04-11');
INSERT INTO sales (region, amount, sale_date) VALUES ('East',  1815.30, DATE '2026-04-18');
INSERT INTO sales (region, amount, sale_date) VALUES ('West',   712.00, DATE '2026-04-27');
INSERT INTO sales (region, amount, sale_date) VALUES ('North', 2340.50, DATE '2026-05-06');
INSERT INTO sales (region, amount, sale_date) VALUES ('South', 1155.00, DATE '2026-05-14');
INSERT INTO sales (region, amount, sale_date) VALUES ('East',   835.25, DATE '2026-05-22');
INSERT INTO sales (region, amount, sale_date) VALUES ('West',  1980.00, DATE '2026-06-01');
INSERT INTO sales (region, amount, sale_date) VALUES ('North', 1425.60, DATE '2026-06-09');
INSERT INTO sales (region, amount, sale_date) VALUES ('South',  605.00, DATE '2026-06-17');
INSERT INTO sales (region, amount, sale_date) VALUES ('East',  2050.75, DATE '2026-06-25');
INSERT INTO sales (region, amount, sale_date) VALUES ('West',   890.00, DATE '2026-07-04');

COMMIT;
